### ISSUE TITLE
Host decides when to leave boat

### ISSUE THREAD

**Issue by vanny96** [vanny96/GlobalGameJam2022#13]

**Comment by vanny96** [comment]
Do you think we might need a bigger boat for this?

**Comment by Jelligeth** [comment]
I will try to make the boar bigger!

**Comment by Jelligeth** [comment]
I will also add spawnpoints to the boat (that a programmer will need to hook up to code) so the players don't all spawn on top of each other

**Comment by vanny96** [comment]
Linked the ability to Start the game to the "Enter" button, I think now the only thing that is missing is an UI element that could indicate if the game has started
