### ISSUE TITLE
Universal indication when a player is in danger

### ISSUE THREAD

**Issue by Jelligeth** [vanny96/GlobalGameJam2022#25]
-Musical sting
-Vignette closing in around screen border
-Maybe a message pops up like with beacon (quick pop up)

**Comment by vanny96** [comment]
Added message on https://github.com/vanny96/GlobalGameJam2022/commit/cb26c7a931d5d7a1ab2090a1c40d09d2e05cb084

**Comment by vanny96** [comment]
Added vignette on 9d431d7
